Создание/удаление на сервере, блокировка, лоадер, покачивание
htmlacademy-ecmascript/2325181-big-trip-20 pull request #13
Opened 2023-06-07 09:34 UTC by cruzr1

Привет, Николай!

Подготовил ДЗ 8.9:
1) Добавил методы создания новых точек  и удаления точек на сервере. В случае ошибки вызывается метод покачивания.
2) Настроил форму редактирования точки на изменение текста кнопок и блокировки полей во время загрузки. Также добавил блокировку интерфейса лоадером. После успешного ответа интерфейс разблокируется тексты кнопок возвращаются к прежним значениям.

С уважением,
Ринат.

2023-06-07 17:03 UTC, NikolaiKotikov requested changes
По новому функционалу ок, со старым есть пара моментов:
- офферы перестали выбираться 
![image](https://github.com/htmlacademy-ecmascript/2325181-big-trip-20/assets/45531639/e5ed1700-fdcf-4c2b-bbde-986b38daadd4)

- периодически выскакивает ошибка загрузки, хотя данные загружаются (нужно перезагрузить несколько раз)
![image](https://github.com/htmlacademy-ecmascript/2325181-big-trip-20/assets/45531639/1b512d91-59e0-4523-9b2f-f48bce796498)

Чекни что там не так плис, будут вопросы - велкам!

2023-06-07 17:03 UTC, NikolaiKotikov commented on src/presenter/event-add-presenter.js
> +    const resetPointState = this.#editionFormComponent.updateElement({
Не понял, зачем тут переменная `resetPointState` ?
Метод `updateElement` ничего не возвращает

2023-06-07 17:03 UTC, NikolaiKotikov commented on src/points-api-service.js
> +      url: 'big-trip/points',
В прошлый раз не обратил внимания, но лучше все сегменты URL вынести в константы, так как они
повторятся в нескольких местах

2023-06-07 23:16 UTC, cruzr1 commented
Привет, Николай!

Спасибо большое за проверку и замечания!
1) Поправил по комментариям: вынес сегменты URL в константы, добавил стрелочную функцию для resetPointState, т.к. это колбэк который должен запуститься после завершения "потряхивания" формы при ошибке отправки. 
2) Насчет ошибки загрузки доп. данных (офферы, города)  - вывел асинхронные методы моделей  - init()  - и весь последующий  код отрисовки в отдельный приватный метод презентера маршрута. После загрузки точек модель уведомляет презентер и тот вызывает приватный метод. Таким образом, отрисовка происходит только по результатам ответа сервера по всем трем структурам.
3) Проверил офферы - у меня все выделяется, сохраняется и отменяется, работает для новых и существующих точек. Уточни пожалуйста в какой момент возникает ошибка?

С уважением, 
Ринат.

2023-06-08 09:45 UTC, NikolaiKotikov approved these changes
- Интерфейс обновляется только после загрузки данных ✅
- Офферы корректно выделяются ✅ 
Спасибо что проверил, видимо у меня был какой-то глюк 😼

По остальному - ок, молодец, у меня пока замечаний больше нет 👌

2023-06-08 09:45 UTC, merged